#! usr/bin/python
# encoding=utf-8

__author__ = 'a1opex'

import math

from base import ProblemBase

class Problem(ProblemBase):
    """
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?
    """
    index = 12
    name = "Highly divisible triangular number"

    tmp = 0

    def main(self):
        for i in xrange(1, 1000000):
            self.tmp +=  i
            count = 0
            for j in xrange(1, int(math.sqrt(self.tmp))+1):
                if self.tmp % j == 0:
                    count += 2
                if int(math.sqrt(self.tmp)) == math.sqrt(self.tmp):
                    count -= 1
                if count >= 500:
                    return self.tmp
